wasm_test!(minimal_threadlocal, "minimal-threadlocal");
wasm_test!(minimal_threadlocals, "minimal-threadlocals");
wasm_test!(dl_tls, "dl-tls");
wasm_test!(
    thread_getspecific_in_main_thread,
    "thread-getspecific-in-main-thread"
);
wasm_test!(threadlocal_errno, "threadlocal-errno");
wasm_test!(
    threadlocal_defined_in_main_used_in_shared_lib,
    "threadlocal-defined-in-main-used-in-shared-lib"
);
wasm_test!(threadlocal_in_shared_lib, "threadlocal-in-shared-lib");
wasm_test!(
    threadlocals_are_actually_threadlocal,
    "threadlocals-are-actually-threadlocal"
);
wasm_test!(
    threadlocals_work_in_a_shared_lib,
    "threadlocals-work-in-a-shared-lib"
);
wasm_test!(
    threadlocals_work_in_a_shared_lib_weird,
    "threadlocals-work-in-a-shared-lib-weird"
);
wasm_test!(extern_threadlocal, "extern-threadlocal");
wasm_test!(extern_threadlocal_nopic, "extern-threadlocal-nopic");
wasm_test!(
    tsd_set_direct_in_direct_get_direct_in_direct,
    "tsd-set-DIRECT-in-DIRECT-get-DIRECT-in-DIRECT"
);
wasm_test!(
    tsd_set_direct_in_direct_get_direct_in_shared,
    "tsd-set-DIRECT-in-DIRECT-get-DIRECT-in-SHARED"
);
wasm_test!(
    tsd_set_direct_in_direct_get_direct_in_dynamic,
    "tsd-set-DIRECT-in-DIRECT-get-DIRECT-in-DYNAMIC"
);
wasm_test!(
    tsd_set_direct_in_direct_get_shared_in_direct,
    "tsd-set-DIRECT-in-DIRECT-get-SHARED-in-DIRECT"
);
wasm_test!(
    tsd_set_direct_in_direct_get_shared_in_shared,
    "tsd-set-DIRECT-in-DIRECT-get-SHARED-in-SHARED"
);
wasm_test!(
    tsd_set_direct_in_direct_get_shared_in_dynamic,
    "tsd-set-DIRECT-in-DIRECT-get-SHARED-in-DYNAMIC"
);
wasm_test!(
    tsd_set_direct_in_direct_get_dynamic_in_direct,
    "tsd-set-DIRECT-in-DIRECT-get-DYNAMIC-in-DIRECT"
);
wasm_test!(
    tsd_set_direct_in_direct_get_dynamic_in_shared,
    "tsd-set-DIRECT-in-DIRECT-get-DYNAMIC-in-SHARED"
);
wasm_test!(
    tsd_set_direct_in_direct_get_dynamic_in_dynamic,
    "tsd-set-DIRECT-in-DIRECT-get-DYNAMIC-in-DYNAMIC"
);
wasm_test!(
    tsd_set_direct_in_shared_get_direct_in_direct,
    "tsd-set-DIRECT-in-SHARED-get-DIRECT-in-DIRECT"
);
wasm_test!(
    tsd_set_direct_in_shared_get_direct_in_shared,
    "tsd-set-DIRECT-in-SHARED-get-DIRECT-in-SHARED"
);
wasm_test!(
    tsd_set_direct_in_shared_get_direct_in_dynamic,
    "tsd-set-DIRECT-in-SHARED-get-DIRECT-in-DYNAMIC"
);
wasm_test!(
    tsd_set_direct_in_shared_get_shared_in_direct,
    "tsd-set-DIRECT-in-SHARED-get-SHARED-in-DIRECT"
);
wasm_test!(
    tsd_set_direct_in_shared_get_shared_in_shared,
    "tsd-set-DIRECT-in-SHARED-get-SHARED-in-SHARED"
);
wasm_test!(
    tsd_set_direct_in_shared_get_shared_in_dynamic,
    "tsd-set-DIRECT-in-SHARED-get-SHARED-in-DYNAMIC"
);
wasm_test!(
    tsd_set_direct_in_shared_get_dynamic_in_direct,
    "tsd-set-DIRECT-in-SHARED-get-DYNAMIC-in-DIRECT"
);
wasm_test!(
    tsd_set_direct_in_shared_get_dynamic_in_shared,
    "tsd-set-DIRECT-in-SHARED-get-DYNAMIC-in-SHARED"
);
wasm_test!(
    tsd_set_direct_in_shared_get_dynamic_in_dynamic,
    "tsd-set-DIRECT-in-SHARED-get-DYNAMIC-in-DYNAMIC"
);
wasm_test!(
    tsd_set_direct_in_dynamic_get_direct_in_direct,
    "tsd-set-DIRECT-in-DYNAMIC-get-DIRECT-in-DIRECT"
);
wasm_test!(
    tsd_set_direct_in_dynamic_get_direct_in_shared,
    "tsd-set-DIRECT-in-DYNAMIC-get-DIRECT-in-SHARED"
);
wasm_test!(
    tsd_set_direct_in_dynamic_get_direct_in_dynamic,
    "tsd-set-DIRECT-in-DYNAMIC-get-DIRECT-in-DYNAMIC"
);
wasm_test!(
    tsd_set_direct_in_dynamic_get_shared_in_direct,
    "tsd-set-DIRECT-in-DYNAMIC-get-SHARED-in-DIRECT"
);
wasm_test!(
    tsd_set_direct_in_dynamic_get_shared_in_shared,
    "tsd-set-DIRECT-in-DYNAMIC-get-SHARED-in-SHARED"
);
wasm_test!(
    tsd_set_direct_in_dynamic_get_shared_in_dynamic,
    "tsd-set-DIRECT-in-DYNAMIC-get-SHARED-in-DYNAMIC"
);
wasm_test!(
    tsd_set_direct_in_dynamic_get_dynamic_in_direct,
    "tsd-set-DIRECT-in-DYNAMIC-get-DYNAMIC-in-DIRECT"
);
wasm_test!(
    tsd_set_direct_in_dynamic_get_dynamic_in_shared,
    "tsd-set-DIRECT-in-DYNAMIC-get-DYNAMIC-in-SHARED"
);
wasm_test!(
    tsd_set_direct_in_dynamic_get_dynamic_in_dynamic,
    "tsd-set-DIRECT-in-DYNAMIC-get-DYNAMIC-in-DYNAMIC"
);
wasm_test!(
    tsd_set_shared_in_direct_get_direct_in_direct,
    "tsd-set-SHARED-in-DIRECT-get-DIRECT-in-DIRECT"
);
wasm_test!(
    tsd_set_shared_in_direct_get_direct_in_shared,
    "tsd-set-SHARED-in-DIRECT-get-DIRECT-in-SHARED"
);
wasm_test!(
    tsd_set_shared_in_direct_get_direct_in_dynamic,
    "tsd-set-SHARED-in-DIRECT-get-DIRECT-in-DYNAMIC"
);
wasm_test!(
    tsd_set_shared_in_direct_get_shared_in_direct,
    "tsd-set-SHARED-in-DIRECT-get-SHARED-in-DIRECT"
);
wasm_test!(
    tsd_set_shared_in_direct_get_shared_in_shared,
    "tsd-set-SHARED-in-DIRECT-get-SHARED-in-SHARED"
);
wasm_test!(
    tsd_set_shared_in_direct_get_shared_in_dynamic,
    "tsd-set-SHARED-in-DIRECT-get-SHARED-in-DYNAMIC"
);
wasm_test!(
    tsd_set_shared_in_direct_get_dynamic_in_direct,
    "tsd-set-SHARED-in-DIRECT-get-DYNAMIC-in-DIRECT"
);
wasm_test!(
    tsd_set_shared_in_direct_get_dynamic_in_shared,
    "tsd-set-SHARED-in-DIRECT-get-DYNAMIC-in-SHARED"
);
wasm_test!(
    tsd_set_shared_in_direct_get_dynamic_in_dynamic,
    "tsd-set-SHARED-in-DIRECT-get-DYNAMIC-in-DYNAMIC"
);
wasm_test!(
    tsd_set_shared_in_shared_get_direct_in_direct,
    "tsd-set-SHARED-in-SHARED-get-DIRECT-in-DIRECT"
);
wasm_test!(
    tsd_set_shared_in_shared_get_direct_in_shared,
    "tsd-set-SHARED-in-SHARED-get-DIRECT-in-SHARED"
);
wasm_test!(
    tsd_set_shared_in_shared_get_direct_in_dynamic,
    "tsd-set-SHARED-in-SHARED-get-DIRECT-in-DYNAMIC"
);
wasm_test!(
    tsd_set_shared_in_shared_get_shared_in_direct,
    "tsd-set-SHARED-in-SHARED-get-SHARED-in-DIRECT"
);
wasm_test!(
    tsd_set_shared_in_shared_get_shared_in_shared,
    "tsd-set-SHARED-in-SHARED-get-SHARED-in-SHARED"
);
wasm_test!(
    tsd_set_shared_in_shared_get_shared_in_dynamic,
    "tsd-set-SHARED-in-SHARED-get-SHARED-in-DYNAMIC"
);
wasm_test!(
    tsd_set_shared_in_shared_get_dynamic_in_direct,
    "tsd-set-SHARED-in-SHARED-get-DYNAMIC-in-DIRECT"
);
wasm_test!(
    tsd_set_shared_in_shared_get_dynamic_in_shared,
    "tsd-set-SHARED-in-SHARED-get-DYNAMIC-in-SHARED"
);
wasm_test!(
    tsd_set_shared_in_shared_get_dynamic_in_dynamic,
    "tsd-set-SHARED-in-SHARED-get-DYNAMIC-in-DYNAMIC"
);
wasm_test!(
    tsd_set_shared_in_dynamic_get_direct_in_direct,
    "tsd-set-SHARED-in-DYNAMIC-get-DIRECT-in-DIRECT"
);
wasm_test!(
    tsd_set_shared_in_dynamic_get_direct_in_shared,
    "tsd-set-SHARED-in-DYNAMIC-get-DIRECT-in-SHARED"
);
wasm_test!(
    tsd_set_shared_in_dynamic_get_direct_in_dynamic,
    "tsd-set-SHARED-in-DYNAMIC-get-DIRECT-in-DYNAMIC"
);
wasm_test!(
    tsd_set_shared_in_dynamic_get_shared_in_direct,
    "tsd-set-SHARED-in-DYNAMIC-get-SHARED-in-DIRECT"
);
wasm_test!(
    tsd_set_shared_in_dynamic_get_shared_in_shared,
    "tsd-set-SHARED-in-DYNAMIC-get-SHARED-in-SHARED"
);
wasm_test!(
    tsd_set_shared_in_dynamic_get_shared_in_dynamic,
    "tsd-set-SHARED-in-DYNAMIC-get-SHARED-in-DYNAMIC"
);
wasm_test!(
    tsd_set_shared_in_dynamic_get_dynamic_in_direct,
    "tsd-set-SHARED-in-DYNAMIC-get-DYNAMIC-in-DIRECT"
);
wasm_test!(
    tsd_set_shared_in_dynamic_get_dynamic_in_shared,
    "tsd-set-SHARED-in-DYNAMIC-get-DYNAMIC-in-SHARED"
);
wasm_test!(
    tsd_set_shared_in_dynamic_get_dynamic_in_dynamic,
    "tsd-set-SHARED-in-DYNAMIC-get-DYNAMIC-in-DYNAMIC"
);
wasm_test!(
    tsd_set_dynamic_in_direct_get_direct_in_direct,
    "tsd-set-DYNAMIC-in-DIRECT-get-DIRECT-in-DIRECT"
);
wasm_test!(
    tsd_set_dynamic_in_direct_get_direct_in_shared,
    "tsd-set-DYNAMIC-in-DIRECT-get-DIRECT-in-SHARED"
);
wasm_test!(
    tsd_set_dynamic_in_direct_get_direct_in_dynamic,
    "tsd-set-DYNAMIC-in-DIRECT-get-DIRECT-in-DYNAMIC"
);
wasm_test!(
    tsd_set_dynamic_in_direct_get_shared_in_direct,
    "tsd-set-DYNAMIC-in-DIRECT-get-SHARED-in-DIRECT"
);
wasm_test!(
    tsd_set_dynamic_in_direct_get_shared_in_shared,
    "tsd-set-DYNAMIC-in-DIRECT-get-SHARED-in-SHARED"
);
wasm_test!(
    tsd_set_dynamic_in_direct_get_shared_in_dynamic,
    "tsd-set-DYNAMIC-in-DIRECT-get-SHARED-in-DYNAMIC"
);
wasm_test!(
    tsd_set_dynamic_in_direct_get_dynamic_in_direct,
    "tsd-set-DYNAMIC-in-DIRECT-get-DYNAMIC-in-DIRECT"
);
wasm_test!(
    tsd_set_dynamic_in_direct_get_dynamic_in_shared,
    "tsd-set-DYNAMIC-in-DIRECT-get-DYNAMIC-in-SHARED"
);
wasm_test!(
    tsd_set_dynamic_in_direct_get_dynamic_in_dynamic,
    "tsd-set-DYNAMIC-in-DIRECT-get-DYNAMIC-in-DYNAMIC"
);
wasm_test!(
    tsd_set_dynamic_in_shared_get_direct_in_direct,
    "tsd-set-DYNAMIC-in-SHARED-get-DIRECT-in-DIRECT"
);
wasm_test!(
    tsd_set_dynamic_in_shared_get_direct_in_shared,
    "tsd-set-DYNAMIC-in-SHARED-get-DIRECT-in-SHARED"
);
wasm_test!(
    tsd_set_dynamic_in_shared_get_direct_in_dynamic,
    "tsd-set-DYNAMIC-in-SHARED-get-DIRECT-in-DYNAMIC"
);
wasm_test!(
    tsd_set_dynamic_in_shared_get_shared_in_direct,
    "tsd-set-DYNAMIC-in-SHARED-get-SHARED-in-DIRECT"
);
wasm_test!(
    tsd_set_dynamic_in_shared_get_shared_in_shared,
    "tsd-set-DYNAMIC-in-SHARED-get-SHARED-in-SHARED"
);
wasm_test!(
    tsd_set_dynamic_in_shared_get_shared_in_dynamic,
    "tsd-set-DYNAMIC-in-SHARED-get-SHARED-in-DYNAMIC"
);
wasm_test!(
    tsd_set_dynamic_in_shared_get_dynamic_in_direct,
    "tsd-set-DYNAMIC-in-SHARED-get-DYNAMIC-in-DIRECT"
);
wasm_test!(
    tsd_set_dynamic_in_shared_get_dynamic_in_shared,
    "tsd-set-DYNAMIC-in-SHARED-get-DYNAMIC-in-SHARED"
);
wasm_test!(
    tsd_set_dynamic_in_shared_get_dynamic_in_dynamic,
    "tsd-set-DYNAMIC-in-SHARED-get-DYNAMIC-in-DYNAMIC"
);
wasm_test!(
    tsd_set_dynamic_in_dynamic_get_direct_in_direct,
    "tsd-set-DYNAMIC-in-DYNAMIC-get-DIRECT-in-DIRECT"
);
wasm_test!(
    tsd_set_dynamic_in_dynamic_get_direct_in_shared,
    "tsd-set-DYNAMIC-in-DYNAMIC-get-DIRECT-in-SHARED"
);
wasm_test!(
    tsd_set_dynamic_in_dynamic_get_direct_in_dynamic,
    "tsd-set-DYNAMIC-in-DYNAMIC-get-DIRECT-in-DYNAMIC"
);
wasm_test!(
    tsd_set_dynamic_in_dynamic_get_shared_in_direct,
    "tsd-set-DYNAMIC-in-DYNAMIC-get-SHARED-in-DIRECT"
);
wasm_test!(
    tsd_set_dynamic_in_dynamic_get_shared_in_shared,
    "tsd-set-DYNAMIC-in-DYNAMIC-get-SHARED-in-SHARED"
);
wasm_test!(
    tsd_set_dynamic_in_dynamic_get_shared_in_dynamic,
    "tsd-set-DYNAMIC-in-DYNAMIC-get-SHARED-in-DYNAMIC"
);
wasm_test!(
    tsd_set_dynamic_in_dynamic_get_dynamic_in_direct,
    "tsd-set-DYNAMIC-in-DYNAMIC-get-DYNAMIC-in-DIRECT"
);
wasm_test!(
    tsd_set_dynamic_in_dynamic_get_dynamic_in_shared,
    "tsd-set-DYNAMIC-in-DYNAMIC-get-DYNAMIC-in-SHARED"
);
wasm_test!(
    tsd_set_dynamic_in_dynamic_get_dynamic_in_dynamic,
    "tsd-set-DYNAMIC-in-DYNAMIC-get-DYNAMIC-in-DYNAMIC"
);
