var annotated_dup =
[
    [ "wasmer_byte_array", "structwasmer__byte__array.html", "structwasmer__byte__array" ],
    [ "wasmer_export_descriptor_t", "structwasmer__export__descriptor__t.html", null ],
    [ "wasmer_export_descriptors_t", "structwasmer__export__descriptors__t.html", null ],
    [ "wasmer_export_func_t", "structwasmer__export__func__t.html", null ],
    [ "wasmer_export_t", "structwasmer__export__t.html", null ],
    [ "wasmer_exports_t", "structwasmer__exports__t.html", null ],
    [ "wasmer_global_descriptor_t", "structwasmer__global__descriptor__t.html", "structwasmer__global__descriptor__t" ],
    [ "wasmer_global_t", "structwasmer__global__t.html", null ],
    [ "wasmer_import_descriptor_t", "structwasmer__import__descriptor__t.html", null ],
    [ "wasmer_import_descriptors_t", "structwasmer__import__descriptors__t.html", null ],
    [ "wasmer_import_export_value", "unionwasmer__import__export__value.html", "unionwasmer__import__export__value" ],
    [ "wasmer_import_func_t", "structwasmer__import__func__t.html", null ],
    [ "wasmer_import_object_iter_t", "structwasmer__import__object__iter__t.html", null ],
    [ "wasmer_import_object_t", "structwasmer__import__object__t.html", null ],
    [ "wasmer_import_t", "structwasmer__import__t.html", "structwasmer__import__t" ],
    [ "wasmer_instance_context_t", "structwasmer__instance__context__t.html", null ],
    [ "wasmer_instance_t", "structwasmer__instance__t.html", null ],
    [ "wasmer_limit_option_t", "structwasmer__limit__option__t.html", "structwasmer__limit__option__t" ],
    [ "wasmer_limits_t", "structwasmer__limits__t.html", "structwasmer__limits__t" ],
    [ "wasmer_memory_t", "structwasmer__memory__t.html", null ],
    [ "wasmer_module_t", "structwasmer__module__t.html", null ],
    [ "wasmer_serialized_module_t", "structwasmer__serialized__module__t.html", null ],
    [ "wasmer_table_t", "structwasmer__table__t.html", null ],
    [ "wasmer_value", "unionwasmer__value.html", "unionwasmer__value" ],
    [ "wasmer_value_t", "structwasmer__value__t.html", "structwasmer__value__t" ],
    [ "wasmer_wasi_map_dir_entry_t", "structwasmer__wasi__map__dir__entry__t.html", "structwasmer__wasi__map__dir__entry__t" ]
];