name: Load Rust Toolchain
description: Load Rust toolchain from rust-toolchain file
outputs:
  rust_toolchain:
    description: The loaded Rust toolchain
    value: ${{ steps.load_toolchain.outputs.rust_toolchain }}
runs:
  using: composite
  steps:
    - name: Load toolchain
      id: load_toolchain
      run: |
        # TODO: Actually parse this from Cargo.toml
        rust_toolchain=$(head -n1 rust-toolchain | tr -d '\n')
        echo "rust_toolchain=$rust_toolchain" >> $GITHUB_OUTPUT