[files]
extend-exclude = [
  "target",
  "Cargo.lock",
  ".git",
  "node_modules",
  # Exclude non english docs
  "docs/cn",
  "docs/de",
  "docs/es",
  "docs/fr",
  "docs/ja",
  "docs/ko",
  "wasmer-test-files",
  "assets",
  # Exclude specific test data that isn't code
  "*.stdout",
  "*.stderr",
  "*.stdin",
  "*.wasm",
  "*.wast",
  "*.out",
  "*.inc",
  "*.txt",
  "*.md.out",
  "tests/wast/spec/",
  "CHANGELOG.md",
  "**/CHANGELOG.md",
  # external submodule
  "lib/napi",

]

[default.extend-words]
# Global technical terms and valid abbreviations
FPR = "FPR"
fpr = "fpr"
neon = "neon"
alow = "alow"
fle = "fle"
GPR = "GPR"
gpr = "gpr"
Wasm = "Wasm"
wasm = "wasm"
WASI = "WASI"
wasi = "wasi"
exnref = "exnref"
olt = "olt"
OLT = "OLT"
canonicalizations = "canonicalizations"
dynasm = "dynasm"
fp_olt_md = "fp_olt_md"
Ot = "Ot"
Five = "Five"
Binfmt = "Binfmt"
binfmt = "binfmt"
Wapm = "Wapm"
wapm = "wapm"
structuredClone = "structuredClone"
metering = "metering"
Wasmer = "Wasmer"
wasmer = "wasmer"
unstable = "unstable"
fd_memory = "fd_memory"
wcgi = "wcgi"
effector = "effector"
exec3 = "exec3"
oneoff = "oneoff"
bridge = "bridge"
libcalls = "libcalls"
probestack = "probestack"
traphandlers = "traphandlers"
unwind = "unwind"
obj = "obj"
inner = "inner"
mmap = "mmap"
pretty_duration = "pretty_duration"
snapshot_trigger = "snapshot_trigger"
arc_file = "arc_file"
host_fs = "host_fs"
mount_fs = "mount_fs"
null_file = "null_file"
overlay_fs = "overlay_fs"
virtual_net = "virtual_net"
proc_join = "proc_join"
thread_id = "thread_id"
sock_get_opt_flag = "sock_get_opt_flag"
path_unlink_file = "path_unlink_file"
wai_bindgen_wasmer = "wai_bindgen_wasmer"
wasmer_create_exe_main = "wasmer_create_exe_main"
c_gen = "c_gen"
package_wizard = "package_wizard"
GenCHeader = "GenCHeader"
abd = "abd"
ba = "ba"
sems = "sems"
clen = "clen"
daa = "daa"
HOM = "HOM"
informational = "informational"
negativ = "negativ"
oOtQIDI7q = "oOtQIDI7q"
_oOtQIDI7q = "_oOtQIDI7q"
lala_oOtQIDI7q = "lala_oOtQIDI7q"
ACCES = "ACCES"
# Scene ID
tne = "tne"
