(module
    (func $main (export "main")
        (if (i32.eq (select
                (i32.const 10)
                (i32.const 20)
                (i32.const 1)
            ) (i32.const 10))
            (then)
            (else (unreachable))
        )
        (if (i32.eq (select
                (i32.const 10)
                (i32.const 20)
                (i32.const 0)
            ) (i32.const 20))
            (then)
            (else (unreachable))
        )
    )
)
