(module
    (func $main (export "main")
        (i32.const 5)
        (block (result i32)
            (i32.const 10)
            (block
                (i32.const 20)
                (block
                    (i32.const 50)
                    (br 1)
                )
                (unreachable)
            )
        )
        (i32.add)
        (if (i32.eq (i32.const 15))
            (then)
            (else unreachable)
        )

        (block (result i32)
            (i32.const 10)
            (block (result i32)
                (i32.const 20)
                (block
                    (i32.const 50)
                    (br 1)
                )
                (unreachable)
            )
            (i32.add)
        )
        (if (i32.eq (i32.const 60))
            (then)
            (else unreachable)
        )
    )
)
