(function() {var implementors = {};
implementors["wasmer_runtime"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"wasmer_runtime/enum.Backend.html\" title=\"enum wasmer_runtime::Backend\">Backend</a>","synthetic":false,"types":["wasmer_runtime::Backend"]}];
implementors["wasmer_runtime_core"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmer_runtime_core/fault/struct.BoundaryRegisterPreservation.html\" title=\"struct wasmer_runtime_core::fault::BoundaryRegisterPreservation\">BoundaryRegisterPreservation</a>","synthetic":false,"types":["wasmer_runtime_core::fault::BoundaryRegisterPreservation"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmer_runtime_core/state/struct.MachineStateDiff.html\" title=\"struct wasmer_runtime_core::state::MachineStateDiff\">MachineStateDiff</a>","synthetic":false,"types":["wasmer_runtime_core::state::MachineStateDiff"]}];
implementors["wasmer_wasi"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmer_wasi/state/struct.WasiStateBuilder.html\" title=\"struct wasmer_wasi::state::WasiStateBuilder\">WasiStateBuilder</a>","synthetic":false,"types":["wasmer_wasi::state::builder::WasiStateBuilder"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmer_wasi/types/struct.__wasi_filestat_t.html\" title=\"struct wasmer_wasi::types::__wasi_filestat_t\">__wasi_filestat_t</a>","synthetic":false,"types":["wasmer_wasi::syscalls::types::__wasi_filestat_t"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()