// Rust test file autogenerated with cargo build (src/build_spectests.rs).
// Please do NOT modify it by hand, as it will be reseted on next build.
// Test based on spectests/br.wast
#![allow(
    warnings,
    dead_code
)]
use crate::webassembly::{instantiate, compile, ImportObject, ResultObject, VmCtx, Export};
use super::_common::spectest_importobject;
use wabt::wat2wasm;


// Line 3
fn create_module_1() -> ResultObject {
    let module_str = "(module
      (type (;0;) (func (param i32 i32 i32) (result i32)))
      (type (;1;) (func))
      (type (;2;) (func (result i32)))
      (type (;3;) (func (result i64)))
      (type (;4;) (func (result f32)))
      (type (;5;) (func (result f64)))
      (type (;6;) (func (param i32 i32) (result i32)))
      (func (;0;) (type 1))
      (func (;1;) (type 1)
        block  ;; label = @1
          br 0 (;@1;)
          i32.ctz
          drop
        end)
      (func (;2;) (type 1)
        block  ;; label = @1
          br 0 (;@1;)
          i64.ctz
          drop
        end)
      (func (;3;) (type 1)
        block  ;; label = @1
          br 0 (;@1;)
          f32.neg
          drop
        end)
      (func (;4;) (type 1)
        block  ;; label = @1
          br 0 (;@1;)
          f64.neg
          drop
        end)
      (func (;5;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 1
          br 0 (;@1;)
          i32.ctz
        end)
      (func (;6;) (type 3) (result i64)
        block (result i64)  ;; label = @1
          i64.const 2
          br 0 (;@1;)
          i64.ctz
        end)
      (func (;7;) (type 4) (result f32)
        block (result f32)  ;; label = @1
          f32.const 0x1.8p+1 (;=3;)
          br 0 (;@1;)
          f32.neg
        end)
      (func (;8;) (type 5) (result f64)
        block (result f64)  ;; label = @1
          f64.const 0x1p+2 (;=4;)
          br 0 (;@1;)
          f64.neg
        end)
      (func (;9;) (type 1)
        block  ;; label = @1
          br 0 (;@1;)
          call 0
        end)
      (func (;10;) (type 1)
        block  ;; label = @1
          call 0
          br 0 (;@1;)
          call 0
        end)
      (func (;11;) (type 1)
        block  ;; label = @1
          nop
          call 0
          br 0 (;@1;)
        end)
      (func (;12;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          nop
          call 0
          i32.const 2
          br 0 (;@1;)
        end)
      (func (;13;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          loop (result i32)  ;; label = @2
            i32.const 3
            br 1 (;@1;)
            i32.const 2
          end
        end)
      (func (;14;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          loop (result i32)  ;; label = @2
            call 0
            i32.const 4
            br 1 (;@1;)
            i32.const 2
          end
        end)
      (func (;15;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          loop (result i32)  ;; label = @2
            nop
            call 0
            i32.const 5
            br 1 (;@1;)
          end
        end)
      (func (;16;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 9
          br 0 (;@1;)
          br 0 (;@1;)
        end)
      (func (;17;) (type 1)
        block  ;; label = @1
          br 0 (;@1;)
          br_if 0 (;@1;)
        end)
      (func (;18;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 8
          br 0 (;@1;)
          i32.const 1
          br_if 0 (;@1;)
          drop
          i32.const 7
        end)
      (func (;19;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 6
          i32.const 9
          br 0 (;@1;)
          br_if 0 (;@1;)
          drop
          i32.const 7
        end)
      (func (;20;) (type 1)
        block  ;; label = @1
          br 0 (;@1;)
          br_table 0 (;@1;) 0 (;@1;) 0 (;@1;)
        end)
      (func (;21;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 10
          br 0 (;@1;)
          i32.const 1
          br_table 0 (;@1;) 0 (;@1;) 0 (;@1;)
          i32.const 7
        end)
      (func (;22;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 6
          i32.const 11
          br 0 (;@1;)
          br_table 0 (;@1;) 0 (;@1;)
          i32.const 7
        end)
      (func (;23;) (type 3) (result i64)
        block (result i64)  ;; label = @1
          i64.const 7
          br 0 (;@1;)
          return
        end)
      (func (;24;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 2
          br 0 (;@1;)
          if (result i32)  ;; label = @2
            i32.const 0
          else
            i32.const 1
          end
        end)
      (func (;25;) (type 6) (param i32 i32) (result i32)
        block (result i32)  ;; label = @1
          get_local 0
          if (result i32)  ;; label = @2
            i32.const 3
            br 1 (;@1;)
          else
            get_local 1
          end
        end)
      (func (;26;) (type 6) (param i32 i32) (result i32)
        block (result i32)  ;; label = @1
          get_local 0
          if (result i32)  ;; label = @2
            get_local 1
          else
            i32.const 4
            br 1 (;@1;)
          end
        end)
      (func (;27;) (type 6) (param i32 i32) (result i32)
        block (result i32)  ;; label = @1
          i32.const 5
          br 0 (;@1;)
          get_local 0
          get_local 1
          select
        end)
      (func (;28;) (type 6) (param i32 i32) (result i32)
        block (result i32)  ;; label = @1
          get_local 0
          i32.const 6
          br 0 (;@1;)
          get_local 1
          select
        end)
      (func (;29;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 0
          i32.const 1
          i32.const 7
          br 0 (;@1;)
          select
        end)
      (func (;30;) (type 0) (param i32 i32 i32) (result i32)
        i32.const -1)
      (func (;31;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 12
          br 0 (;@1;)
          i32.const 2
          i32.const 3
          call 30
        end)
      (func (;32;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 1
          i32.const 13
          br 0 (;@1;)
          i32.const 3
          call 30
        end)
      (func (;33;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 1
          i32.const 2
          i32.const 14
          br 0 (;@1;)
          call 30
        end)
      (func (;34;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 20
          br 0 (;@1;)
          i32.const 1
          i32.const 2
          i32.const 3
          call_indirect (type 0)
        end)
      (func (;35;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 0
          i32.const 21
          br 0 (;@1;)
          i32.const 2
          i32.const 3
          call_indirect (type 0)
        end)
      (func (;36;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 0
          i32.const 1
          i32.const 22
          br 0 (;@1;)
          i32.const 3
          call_indirect (type 0)
        end)
      (func (;37;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 0
          i32.const 1
          i32.const 2
          i32.const 23
          br 0 (;@1;)
          call_indirect (type 0)
        end)
      (func (;38;) (type 2) (result i32)
        (local f32)
        block (result i32)  ;; label = @1
          i32.const 17
          br 0 (;@1;)
          set_local 0
          i32.const -1
        end)
      (func (;39;) (type 2) (result i32)
        (local i32)
        block (result i32)  ;; label = @1
          i32.const 1
          br 0 (;@1;)
          tee_local 0
        end)
      (func (;40;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 1
          br 0 (;@1;)
          set_global 0
        end)
      (func (;41;) (type 4) (result f32)
        block (result f32)  ;; label = @1
          f32.const 0x1.b33334p+0 (;=1.7;)
          br 0 (;@1;)
          f32.load
        end)
      (func (;42;) (type 3) (result i64)
        block (result i64)  ;; label = @1
          i64.const 30
          br 0 (;@1;)
          i64.load8_s
        end)
      (func (;43;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 30
          br 0 (;@1;)
          f64.const 0x1.cp+2 (;=7;)
          f64.store
          i32.const -1
        end)
      (func (;44;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 2
          i32.const 31
          br 0 (;@1;)
          i64.store
          i32.const -1
        end)
      (func (;45;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 32
          br 0 (;@1;)
          i32.const 7
          i32.store8
          i32.const -1
        end)
      (func (;46;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 2
          i32.const 33
          br 0 (;@1;)
          i64.store16
          i32.const -1
        end)
      (func (;47;) (type 4) (result f32)
        block (result f32)  ;; label = @1
          f32.const 0x1.b33334p+1 (;=3.4;)
          br 0 (;@1;)
          f32.neg
        end)
      (func (;48;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 3
          br 0 (;@1;)
          i32.const 10
          i32.add
        end)
      (func (;49;) (type 3) (result i64)
        block (result i64)  ;; label = @1
          i64.const 10
          i64.const 45
          br 0 (;@1;)
          i64.sub
        end)
      (func (;50;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 44
          br 0 (;@1;)
          i32.eqz
        end)
      (func (;51;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 43
          br 0 (;@1;)
          f64.const 0x1.4p+3 (;=10;)
          f64.le
        end)
      (func (;52;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          f32.const 0x1.4p+3 (;=10;)
          i32.const 42
          br 0 (;@1;)
          f32.ne
        end)
      (func (;53;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 41
          br 0 (;@1;)
          i32.wrap/i64
        end)
      (func (;54;) (type 2) (result i32)
        block (result i32)  ;; label = @1
          i32.const 40
          br 0 (;@1;)
          memory.grow
        end)
      (func (;55;) (type 2) (result i32)
        i32.const 1
        block (result i32)  ;; label = @1
          call 0
          i32.const 4
          i32.const 8
          br 0 (;@1;)
          i32.add
        end
        i32.add)
      (func (;56;) (type 2) (result i32)
        i32.const 1
        block (result i32)  ;; label = @1
          i32.const 2
          drop
          block (result i32)  ;; label = @2
            i32.const 4
            drop
            i32.const 8
            br 1 (;@1;)
            br 0 (;@2;)
          end
          drop
          i32.const 16
        end
        i32.add)
      (func (;57;) (type 2) (result i32)
        i32.const 1
        block (result i32)  ;; label = @1
          i32.const 2
          drop
          block (result i32)  ;; label = @2
            i32.const 4
            drop
            i32.const 8
            br 1 (;@1;)
            i32.const 1
            br_if 0 (;@2;)
            drop
            i32.const 32
          end
          drop
          i32.const 16
        end
        i32.add)
      (func (;58;) (type 2) (result i32)
        i32.const 1
        block (result i32)  ;; label = @1
          i32.const 2
          drop
          i32.const 4
          i32.const 8
          br 0 (;@1;)
          br_if 0 (;@1;)
          drop
          i32.const 16
        end
        i32.add)
      (func (;59;) (type 2) (result i32)
        i32.const 1
        block (result i32)  ;; label = @1
          i32.const 2
          drop
          block (result i32)  ;; label = @2
            i32.const 4
            drop
            i32.const 8
            br 1 (;@1;)
            i32.const 1
            br_table 0 (;@2;)
          end
          drop
          i32.const 16
        end
        i32.add)
      (func (;60;) (type 2) (result i32)
        i32.const 1
        block (result i32)  ;; label = @1
          i32.const 2
          drop
          i32.const 4
          i32.const 8
          br 0 (;@1;)
          br_table 0 (;@1;)
          i32.const 16
        end
        i32.add)
      (table (;0;) 1 1 anyfunc)
      (memory (;0;) 1)
      (global (;0;) (mut i32) (i32.const 10))
      (export \"type-i32\" (func 1))
      (export \"type-i64\" (func 2))
      (export \"type-f32\" (func 3))
      (export \"type-f64\" (func 4))
      (export \"type-i32-value\" (func 5))
      (export \"type-i64-value\" (func 6))
      (export \"type-f32-value\" (func 7))
      (export \"type-f64-value\" (func 8))
      (export \"as-block-first\" (func 9))
      (export \"as-block-mid\" (func 10))
      (export \"as-block-last\" (func 11))
      (export \"as-block-value\" (func 12))
      (export \"as-loop-first\" (func 13))
      (export \"as-loop-mid\" (func 14))
      (export \"as-loop-last\" (func 15))
      (export \"as-br-value\" (func 16))
      (export \"as-br_if-cond\" (func 17))
      (export \"as-br_if-value\" (func 18))
      (export \"as-br_if-value-cond\" (func 19))
      (export \"as-br_table-index\" (func 20))
      (export \"as-br_table-value\" (func 21))
      (export \"as-br_table-value-index\" (func 22))
      (export \"as-return-value\" (func 23))
      (export \"as-if-cond\" (func 24))
      (export \"as-if-then\" (func 25))
      (export \"as-if-else\" (func 26))
      (export \"as-select-first\" (func 27))
      (export \"as-select-second\" (func 28))
      (export \"as-select-cond\" (func 29))
      (export \"as-call-first\" (func 31))
      (export \"as-call-mid\" (func 32))
      (export \"as-call-last\" (func 33))
      (export \"as-call_indirect-func\" (func 34))
      (export \"as-call_indirect-first\" (func 35))
      (export \"as-call_indirect-mid\" (func 36))
      (export \"as-call_indirect-last\" (func 37))
      (export \"as-set_local-value\" (func 38))
      (export \"as-tee_local-value\" (func 39))
      (export \"as-set_global-value\" (func 40))
      (export \"as-load-address\" (func 41))
      (export \"as-loadN-address\" (func 42))
      (export \"as-store-address\" (func 43))
      (export \"as-store-value\" (func 44))
      (export \"as-storeN-address\" (func 45))
      (export \"as-storeN-value\" (func 46))
      (export \"as-unary-operand\" (func 47))
      (export \"as-binary-left\" (func 48))
      (export \"as-binary-right\" (func 49))
      (export \"as-test-operand\" (func 50))
      (export \"as-compare-left\" (func 51))
      (export \"as-compare-right\" (func 52))
      (export \"as-convert-operand\" (func 53))
      (export \"as-memory.grow-size\" (func 54))
      (export \"nested-block-value\" (func 55))
      (export \"nested-br-value\" (func 56))
      (export \"nested-br_if-value\" (func 57))
      (export \"nested-br_if-value-cond\" (func 58))
      (export \"nested-br_table-value\" (func 59))
      (export \"nested-br_table-value-index\" (func 60))
      (elem (i32.const 0) 30))
    ";
    let wasm_binary = wat2wasm(module_str.as_bytes()).expect("WAST not valid or malformed");
    instantiate(wasm_binary, spectest_importobject()).expect("WASM can't be instantiated")
}

// Line 334
fn l334_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l334_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("type-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, ());
}

// Line 335
fn l335_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l335_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("type-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, ());
}

// Line 336
fn l336_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l336_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("type-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, ());
}

// Line 337
fn l337_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l337_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("type-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, ());
}

// Line 339
fn l339_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l339_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("type-i32-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 1 as i32);
}

// Line 340
fn l340_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l340_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("type-i64-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i64 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 2 as i64);
}

// Line 341
fn l341_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l341_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("type-f32-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 3.0 as f32);
}

// Line 342
fn l342_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l342_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("type-f64-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f64 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 4.0 as f64);
}

// Line 344
fn l344_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l344_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-block-first") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, ());
}

// Line 345
fn l345_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l345_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-block-mid") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, ());
}

// Line 346
fn l346_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l346_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-block-last") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, ());
}

// Line 347
fn l347_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l347_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-block-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 2 as i32);
}

// Line 349
fn l349_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l349_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-loop-first") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 3 as i32);
}

// Line 350
fn l350_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l350_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-loop-mid") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 4 as i32);
}

// Line 351
fn l351_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l351_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-loop-last") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 5 as i32);
}

// Line 353
fn l353_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l353_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-br-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 9 as i32);
}

// Line 355
fn l355_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l355_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-br_if-cond") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, ());
}

// Line 356
fn l356_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l356_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-br_if-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 8 as i32);
}

// Line 357
fn l357_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l357_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-br_if-value-cond") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 9 as i32);
}

// Line 359
fn l359_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l359_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-br_table-index") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, ());
}

// Line 360
fn l360_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l360_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-br_table-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 10 as i32);
}

// Line 361
fn l361_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l361_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-br_table-value-index") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 11 as i32);
}

// Line 363
fn l363_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l363_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-return-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i64 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 7 as i64);
}

// Line 365
fn l365_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l365_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-if-cond") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 2 as i32);
}

// Line 366
fn l366_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l366_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-if-then") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i32, &VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(1 as i32, 6 as i32, &vm_context);
    assert_eq!(result, 3 as i32);
}

// Line 367
fn l367_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l367_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-if-then") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i32, &VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(0 as i32, 6 as i32, &vm_context);
    assert_eq!(result, 6 as i32);
}

// Line 368
fn l368_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l368_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-if-else") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i32, &VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(0 as i32, 6 as i32, &vm_context);
    assert_eq!(result, 4 as i32);
}

// Line 369
fn l369_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l369_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-if-else") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i32, &VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(1 as i32, 6 as i32, &vm_context);
    assert_eq!(result, 6 as i32);
}

// Line 371
fn l371_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l371_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-select-first") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i32, &VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(0 as i32, 6 as i32, &vm_context);
    assert_eq!(result, 5 as i32);
}

// Line 372
fn l372_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l372_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-select-first") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i32, &VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(1 as i32, 6 as i32, &vm_context);
    assert_eq!(result, 5 as i32);
}

// Line 373
fn l373_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l373_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-select-second") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i32, &VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(0 as i32, 6 as i32, &vm_context);
    assert_eq!(result, 6 as i32);
}

// Line 374
fn l374_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l374_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-select-second") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i32, &VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(1 as i32, 6 as i32, &vm_context);
    assert_eq!(result, 6 as i32);
}

// Line 375
fn l375_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l375_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-select-cond") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 7 as i32);
}

// Line 377
fn l377_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l377_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-call-first") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 12 as i32);
}

// Line 378
fn l378_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l378_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-call-mid") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 13 as i32);
}

// Line 379
fn l379_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l379_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-call-last") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 14 as i32);
}

// Line 381
fn l381_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l381_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-call_indirect-func") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 20 as i32);
}

// Line 382
fn l382_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l382_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-call_indirect-first") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 21 as i32);
}

// Line 383
fn l383_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l383_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-call_indirect-mid") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 22 as i32);
}

// Line 384
fn l384_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l384_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-call_indirect-last") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 23 as i32);
}

// Line 386
fn l386_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l386_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-set_local-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 17 as i32);
}

// Line 387
fn l387_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l387_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-tee_local-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 1 as i32);
}

// Line 388
fn l388_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l388_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-set_global-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 1 as i32);
}

// Line 390
fn l390_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l390_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-load-address") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 1.7 as f32);
}

// Line 391
fn l391_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l391_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-loadN-address") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i64 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 30 as i64);
}

// Line 393
fn l393_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l393_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-store-address") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 30 as i32);
}

// Line 394
fn l394_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l394_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-store-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 31 as i32);
}

// Line 395
fn l395_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l395_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-storeN-address") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 32 as i32);
}

// Line 396
fn l396_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l396_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-storeN-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 33 as i32);
}

// Line 398
fn l398_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l398_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-unary-operand") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 3.4 as f32);
}

// Line 400
fn l400_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l400_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-binary-left") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 3 as i32);
}

// Line 401
fn l401_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l401_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-binary-right") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i64 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 45 as i64);
}

// Line 403
fn l403_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l403_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-test-operand") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 44 as i32);
}

// Line 405
fn l405_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l405_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-compare-left") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 43 as i32);
}

// Line 406
fn l406_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l406_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-compare-right") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 42 as i32);
}

// Line 408
fn l408_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l408_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-convert-operand") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 41 as i32);
}

// Line 410
fn l410_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l410_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("as-memory.grow-size") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 40 as i32);
}

// Line 412
fn l412_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l412_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("nested-block-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 9 as i32);
}

// Line 413
fn l413_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l413_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("nested-br-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 9 as i32);
}

// Line 414
fn l414_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l414_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("nested-br_if-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 9 as i32);
}

// Line 415
fn l415_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l415_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("nested-br_if-value-cond") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 9 as i32);
}

// Line 416
fn l416_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l416_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("nested-br_table-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 9 as i32);
}

// Line 417
fn l417_assert_return_invoke(result_object: &ResultObject, vm_context: &VmCtx) {
    println!("Executing function {}", "l417_assert_return_invoke");
    let func_index = match result_object.module.info.exports.get("nested-br_table-value-index") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(result_object.instance, func_index);
    let result = invoke_fn(&vm_context);
    assert_eq!(result, 9 as i32);
}

// Line 420
#[test]
fn l420_assert_invalid() {
    let wasm_binary = [0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 0, 1, 127, 3, 2, 1, 0, 10, 11, 1, 9, 0, 2, 127, 12, 0, 65, 1, 11, 11];
    let compilation = compile(wasm_binary.to_vec());
    assert!(compilation.is_err(), "WASM should not compile as is invalid");
}

// Line 427
#[test]
fn l427_assert_invalid() {
    let wasm_binary = [0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 0, 1, 127, 3, 2, 1, 0, 10, 12, 1, 10, 0, 2, 127, 1, 12, 0, 65, 1, 11, 11];
    let compilation = compile(wasm_binary.to_vec());
    assert!(compilation.is_err(), "WASM should not compile as is invalid");
}

// Line 433
#[test]
fn l433_assert_invalid() {
    let wasm_binary = [0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 0, 1, 127, 3, 2, 1, 0, 10, 14, 1, 12, 0, 2, 127, 65, 0, 2, 64, 12, 1, 11, 11, 11];
    let compilation = compile(wasm_binary.to_vec());
    assert!(compilation.is_err(), "WASM should not compile as is invalid");
}

// Line 439
#[test]
fn l439_assert_invalid() {
    let wasm_binary = [0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 0, 1, 127, 3, 2, 1, 0, 10, 13, 1, 11, 0, 2, 127, 66, 1, 12, 0, 65, 1, 11, 11];
    let compilation = compile(wasm_binary.to_vec());
    assert!(compilation.is_err(), "WASM should not compile as is invalid");
}

// Line 446
#[test]
fn l446_assert_invalid() {
    let wasm_binary = [0, 97, 115, 109, 1, 0, 0, 0, 1, 4, 1, 96, 0, 0, 3, 2, 1, 0, 10, 6, 1, 4, 0, 12, 1, 11];
    let compilation = compile(wasm_binary.to_vec());
    assert!(compilation.is_err(), "WASM should not compile as is invalid");
}

// Line 450
#[test]
fn l450_assert_invalid() {
    let wasm_binary = [0, 97, 115, 109, 1, 0, 0, 0, 1, 4, 1, 96, 0, 0, 3, 2, 1, 0, 10, 12, 1, 10, 0, 2, 64, 2, 64, 12, 5, 11, 11, 11];
    let compilation = compile(wasm_binary.to_vec());
    assert!(compilation.is_err(), "WASM should not compile as is invalid");
}

// Line 454
#[test]
fn l454_assert_invalid() {
    let wasm_binary = [0, 97, 115, 109, 1, 0, 0, 0, 1, 4, 1, 96, 0, 0, 3, 2, 1, 0, 10, 10, 1, 8, 0, 12, 129, 128, 128, 128, 1, 11];
    let compilation = compile(wasm_binary.to_vec());
    assert!(compilation.is_err(), "WASM should not compile as is invalid");
}

#[test]
fn test_module_1() {
    let result_object = create_module_1();
    let vm_context = result_object.instance.generate_context();
    // We group the calls together
    l334_assert_return_invoke(&result_object, &vm_context);
    l335_assert_return_invoke(&result_object, &vm_context);
    l336_assert_return_invoke(&result_object, &vm_context);
    l337_assert_return_invoke(&result_object, &vm_context);
    l339_assert_return_invoke(&result_object, &vm_context);
    l340_assert_return_invoke(&result_object, &vm_context);
    l341_assert_return_invoke(&result_object, &vm_context);
    l342_assert_return_invoke(&result_object, &vm_context);
    l344_assert_return_invoke(&result_object, &vm_context);
    l345_assert_return_invoke(&result_object, &vm_context);
    l346_assert_return_invoke(&result_object, &vm_context);
    l347_assert_return_invoke(&result_object, &vm_context);
    l349_assert_return_invoke(&result_object, &vm_context);
    l350_assert_return_invoke(&result_object, &vm_context);
    l351_assert_return_invoke(&result_object, &vm_context);
    l353_assert_return_invoke(&result_object, &vm_context);
    l355_assert_return_invoke(&result_object, &vm_context);
    l356_assert_return_invoke(&result_object, &vm_context);
    l357_assert_return_invoke(&result_object, &vm_context);
    l359_assert_return_invoke(&result_object, &vm_context);
    l360_assert_return_invoke(&result_object, &vm_context);
    l361_assert_return_invoke(&result_object, &vm_context);
    l363_assert_return_invoke(&result_object, &vm_context);
    l365_assert_return_invoke(&result_object, &vm_context);
    l366_assert_return_invoke(&result_object, &vm_context);
    l367_assert_return_invoke(&result_object, &vm_context);
    l368_assert_return_invoke(&result_object, &vm_context);
    l369_assert_return_invoke(&result_object, &vm_context);
    l371_assert_return_invoke(&result_object, &vm_context);
    l372_assert_return_invoke(&result_object, &vm_context);
    l373_assert_return_invoke(&result_object, &vm_context);
    l374_assert_return_invoke(&result_object, &vm_context);
    l375_assert_return_invoke(&result_object, &vm_context);
    l377_assert_return_invoke(&result_object, &vm_context);
    l378_assert_return_invoke(&result_object, &vm_context);
    l379_assert_return_invoke(&result_object, &vm_context);
    l381_assert_return_invoke(&result_object, &vm_context);
    l382_assert_return_invoke(&result_object, &vm_context);
    l383_assert_return_invoke(&result_object, &vm_context);
    l384_assert_return_invoke(&result_object, &vm_context);
    l386_assert_return_invoke(&result_object, &vm_context);
    l387_assert_return_invoke(&result_object, &vm_context);
    l388_assert_return_invoke(&result_object, &vm_context);
    l390_assert_return_invoke(&result_object, &vm_context);
    l391_assert_return_invoke(&result_object, &vm_context);
    l393_assert_return_invoke(&result_object, &vm_context);
    l394_assert_return_invoke(&result_object, &vm_context);
    l395_assert_return_invoke(&result_object, &vm_context);
    l396_assert_return_invoke(&result_object, &vm_context);
    l398_assert_return_invoke(&result_object, &vm_context);
    l400_assert_return_invoke(&result_object, &vm_context);
    l401_assert_return_invoke(&result_object, &vm_context);
    l403_assert_return_invoke(&result_object, &vm_context);
    l405_assert_return_invoke(&result_object, &vm_context);
    l406_assert_return_invoke(&result_object, &vm_context);
    l408_assert_return_invoke(&result_object, &vm_context);
    l410_assert_return_invoke(&result_object, &vm_context);
    l412_assert_return_invoke(&result_object, &vm_context);
    l413_assert_return_invoke(&result_object, &vm_context);
    l414_assert_return_invoke(&result_object, &vm_context);
    l415_assert_return_invoke(&result_object, &vm_context);
    l416_assert_return_invoke(&result_object, &vm_context);
    l417_assert_return_invoke(&result_object, &vm_context);
}
