[unstable]
min-publish-age = true

[registry]
# Even one day makes a big diffence: https://cooldowns.dev/#does-it-actually-work
global-min-publish-age = "3 days"

[resolver]
incompatible-publish-age = "deny"
