(function() {var implementors = {};
implementors["cranelift_codegen"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"cranelift_codegen/isa/enum.LookupError.html\" title=\"enum cranelift_codegen::isa::LookupError\">LookupError</a>",synthetic:false,types:["cranelift_codegen::isa::LookupError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"cranelift_codegen/settings/enum.SetError.html\" title=\"enum cranelift_codegen::settings::SetError\">SetError</a>",synthetic:false,types:["cranelift_codegen::settings::SetError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"cranelift_codegen/verifier/struct.VerifierError.html\" title=\"struct cranelift_codegen::verifier::VerifierError\">VerifierError</a>",synthetic:false,types:["cranelift_codegen::verifier::VerifierError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"cranelift_codegen/verifier/struct.VerifierErrors.html\" title=\"struct cranelift_codegen::verifier::VerifierErrors\">VerifierErrors</a>",synthetic:false,types:["cranelift_codegen::verifier::VerifierErrors"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"cranelift_codegen/enum.CodegenError.html\" title=\"enum cranelift_codegen::CodegenError\">CodegenError</a>",synthetic:false,types:["cranelift_codegen::result::CodegenError"]},];
implementors["failure"] = [];
implementors["target_lexicon"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"target_lexicon/enum.ParseError.html\" title=\"enum target_lexicon::ParseError\">ParseError</a>",synthetic:false,types:["target_lexicon::parse_error::ParseError"]},];
implementors["wasmer_clif_fork_wasm"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"enum\" href=\"wasmer_clif_fork_wasm/enum.WasmError.html\" title=\"enum wasmer_clif_fork_wasm::WasmError\">WasmError</a>",synthetic:false,types:["wasmer_clif_fork_wasm::environ::spec::WasmError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()