[package]
name = "wasmer-package"
version = "0.704.0"
description = "Packaging related types and functions for Wasmer"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webc.workspace = true
wasmer-config = { version = "0.704.0", path = "../config", optional = true }
wasmer-types = { version = "7.4.0", path = "../types", optional = true, features = [
  "detect-wasm-features",
] }
toml = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
shared-buffer = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
thiserror.workspace = true
cfg-if = { workspace = true, optional = true }
ciborium = { workspace = true, optional = true }
semver = { workspace = true, optional = true }
url = { workspace = true, optional = true }
flate2 = { workspace = true, optional = true }
tar = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
ignore = { workspace = true, optional = true }

[target.'cfg(all(target_family = "wasm", target_os = "wasi"))'.dependencies]
libc.workspace = true

[dev-dependencies]
insta = { workspace = true, features = ["filters", "yaml"] }
pretty_assertions.workspace = true
tempfile.workspace = true
regex.workspace = true
ureq.workspace = true
hexdump.workspace = true

[features]
default = ["execution", "authoring", "webc-v3"]
execution = ["dep:bytes", "dep:wasmer-types"]
authoring = [
  "execution",
  "dep:anyhow",
  "dep:cfg-if",
  "dep:ciborium",
  "dep:flate2",
  "dep:ignore",
  "dep:semver",
  "dep:serde",
  "dep:serde_json",
  "dep:sha2",
  "dep:shared-buffer",
  "dep:tar",
  "dep:tempfile",
  "dep:toml",
  "dep:url",
  "dep:wasmer-config",
]
webc-v1 = ["webc/v1"]
webc-v2 = ["webc/v2"]
webc-v3 = ["webc/v3"]
