(module
  (func (export "large-sig-no-params")
    (result i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64 i64)
    (i64.const 1) (i64.const 2) (i64.const 3) (i64.const 4)
    (i64.const 5) (i64.const 6) (i64.const 7) (i64.const 8)
    (i64.const 9) (i64.const 10) (i64.const 11) (i64.const 12)
  )
)

(assert_return
  (invoke "large-sig-no-params")
  (i64.const 1) (i64.const 2) (i64.const 3) (i64.const 4)
  (i64.const 5) (i64.const 6) (i64.const 7) (i64.const 8)
  (i64.const 9) (i64.const 10) (i64.const 11) (i64.const 12)
)

(module
  (func (export "loop-param-br") (result i32)
    (local $iters i32)
    (local $last i32)
    (i32.const 5)
    (loop (param i32)
      (i32.const 1)
      (i32.sub)
      (local.set $last)
      (local.get $iters)
      (i32.const 1)
      (i32.add)
      (local.tee $iters)
      (i32.const 3)
      (i32.lt_u)
      (if
        (then
          (local.get $last)
          (br 1))
      )
    )
    (local.get $last)
  )

  (func (export "loop-param-br-if") (result i32)
    (local $iters i32)
    (local $last i32)
    (i32.const 5)
    (loop (param i32)
      (i32.const 1)
      (i32.sub)
      (local.set $last)
      (local.get $last)
      (local.get $iters)
      (i32.const 1)
      (i32.add)
      (local.tee $iters)
      (i32.const 3)
      (i32.lt_u)
      (br_if 0)
      (drop)
    )
    (local.get $last)
  )

  (func (export "loop-param-br-table-target") (result i32)
    (local $iters i32)
    (local $last i32)
    (block (result i32)
      (i32.const 5)
      (loop (param i32)
        (i32.const 1)
        (i32.sub)
        (local.set $last)
        (local.get $last)
        (local.get $iters)
        (i32.const 1)
        (i32.add)
        (local.tee $iters)
        (i32.const 3)
        (i32.lt_u)
        (i32.eqz)
        (br_table 0 1)
      )
      (unreachable)
    )
  )

  (func (export "loop-param-br-table-default") (result i32)
    (local $iters i32)
    (local $last i32)
    (block (result i32)
      (i32.const 5)
      (loop (param i32)
        (i32.const 1)
        (i32.sub)
        (local.set $last)
        (local.get $last)
        (local.get $iters)
        (i32.const 1)
        (i32.add)
        (local.tee $iters)
        (i32.const 3)
        (i32.lt_u)
        (i32.const 2)
        (i32.mul)
        (br_table 1 1 0)
      )
      (unreachable)
    )
  )
)

(assert_return (invoke "loop-param-br") (i32.const 2))
(assert_return (invoke "loop-param-br-if") (i32.const 2))
(assert_return (invoke "loop-param-br-table-target") (i32.const 2))
(assert_return (invoke "loop-param-br-table-default") (i32.const 2))
