(module
 (type $FUNCSIG$iii (func (param i32 i32) (result i32)))
 (type $FUNCSIG$ii (func (param i32) (result i32)))
 (import "env" "putchar" (func $putchar (param i32) (result i32)))
 (elem (i32.const 0) $multiply)
 (table 1 1 anyfunc)
 (memory $0 1)
 (export "memory" (memory $0))
 (export "main" (func $main))
 (export "mainn" (func $mainn))
 (func $dispatch (; 0 ;) (param $0 i32) (param $1 i32) (param $2 i32) (result i32)
  (call_indirect (type $FUNCSIG$iii)
   (get_local $1)
   (get_local $2)
   (get_local $0)
  )
 )
 (func $multiply (; 1 ;) (type $FUNCSIG$iii) (param $0 i32) (param $1 i32) (result i32)
  (i32.mul
   (get_local $1)
   (get_local $0)
  )
 )
 (func $mainn (; 2 ;) (result i32)
  (call $dispatch
   (i32.const 0)
   (i32.const 20)
   (i32.const 30)
  )
 )
 (func $main (; 3 ;) (result i32)
  (drop
   (call $putchar
    (i32.const 97)
   )
  )
  (i32.const 0)
 )
)
